

CREATE DATABASE BookTracker;


CREATE TABLE IF NOT EXISTS Authors (
	AuthorID INT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS Books (
	BookID INT PRIMARY KEY AUTO_INCREMENT,
	ISBN VARCHAR(20),
	Title varchar(1000),
	PublishedYear INT,
	FOREIGN KEY (AuthorID) REFERENCES Authors(AuthorID),
)

CREATE TABLE IF NOT EXISTS Users (
	UserID INT PRIMARY KEY AUTO_INCREMENT, 
	Username varchar(20),
	Email varchar(50)
);

CREATE TABLE IF NOT EXISTS BookGenres (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	FOREIGN KEY BookkID REFERENCES Books(BookID),
	FOREIGN KEY (GenreID) REFERENCES Genres(GenreID)
);

CREATE TABLE IF NOT EXISTS Genres (
	GenreID INT PRIMARY KEY AUTO_INCREMENT,
	GenreName VARCHAR(20),
);



